import AppKit
import ImageIO

struct ClipboardEntry: Identifiable, Equatable {
    enum Payload: Equatable {
        case text(String)
        case file(URL)
        case image(Data)
    }

    let id = UUID()
    let payload: Payload
    let capturedAt: Date

    var preview: String {
        switch payload {
        case .text(let text): return text.trimmingCharacters(in: .whitespacesAndNewlines)
        case .file(let url): return url.lastPathComponent
        case .image: return "Изображение из буфера"
        }
    }

    var imageBytes: Int {
        if case .image(let data) = payload { return data.count }
        return 0
    }

    var symbol: String {
        switch payload {
        case .text(let text): return URL(string: text)?.scheme == "https" ? "link" : "text.alignleft"
        case .file: return "doc"
        case .image: return "photo"
        }
    }
}

enum ClipboardPolicy {
    static let maxEntries = 30
    /// Не ниже предела заметки: иначе скопированная целиком длинная заметка
    /// молча отвергается, и со стороны это выглядит как «копирование
    /// перестало работать».
    static let maxTextCharacters = NoteStore.maxCharacters
    static let maxImageBytes = 20 * 1_024 * 1_024
    /// Поэлементного лимита мало: тридцать снимков по двадцать мегабайт — это
    /// шестьсот мегабайт в памяти фоновой утилиты.
    static let maxImageBytesTotal = 200 * 1_024 * 1_024
    static let maxImagePixels = 40_000_000

    static let ignoredTypeNames: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Текст, попавший в переводчик, в истории только мешает: его копировали,
    /// чтобы прочитать, а не чтобы хранить. Сравниваем по содержимому без
    /// краевых пробелов — вставка часто приносит их с собой.
    static func removingText(_ text: String, from entries: [ClipboardEntry]) -> [ClipboardEntry] {
        let needle = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty else { return entries }
        return entries.filter { entry in
            guard case .text(let value) = entry.payload else { return true }
            return value.trimmingCharacters(in: .whitespacesAndNewlines) != needle
        }
    }

    static func shouldIgnore(typeNames: [String]) -> Bool {
        !ignoredTypeNames.isDisjoint(with: typeNames)
    }

    static func acceptsImage(_ data: Data) -> Bool {
        guard !data.isEmpty, data.count <= maxImageBytes,
              let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int,
              width > 0, height > 0 else { return false }
        let pixelCount = width.multipliedReportingOverflow(by: height)
        return !pixelCount.overflow
            && width <= 8_192
            && height <= 8_192
            && pixelCount.partialValue <= maxImagePixels
    }
}

enum ClipboardVault {
    static let quotaBytes: Int64 = 250 * 1_024 * 1_024

    static func save(_ png: Data) throws -> URL {
        guard ClipboardPolicy.acceptsImage(png) else { throw VaultError.invalidImage }
        let usage = currentUsage()
        guard usage + Int64(png.count) <= quotaBytes else { throw VaultError.quotaExceeded }
        let url = ApplicationPaths.clipboardVault
            .appendingPathComponent("Clipboard-\(UUID().uuidString).png", isDirectory: false)
        try png.write(to: url, options: [.atomic, .completeFileProtection])
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        return url
    }

    static func currentUsage() -> Int64 {
        guard let urls = try? FileManager.default.contentsOfDirectory(
            at: ApplicationPaths.clipboardVault,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey],
            options: [.skipsHiddenFiles, .skipsSubdirectoryDescendants]
        ) else { return 0 }
        return urls.reduce(0) { total, url in
            let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            guard values?.isRegularFile == true else { return total }
            return total + Int64(values?.fileSize ?? 0)
        }
    }

    static func clear() {
        guard let urls = try? FileManager.default.contentsOfDirectory(
            at: ApplicationPaths.clipboardVault,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles, .skipsSubdirectoryDescendants]
        ) else { return }
        for url in urls {
            guard (try? url.resourceValues(forKeys: [.isRegularFileKey]))?.isRegularFile == true else { continue }
            try? FileManager.default.removeItem(at: url)
        }
    }

    enum VaultError: LocalizedError {
        case invalidImage
        case quotaExceeded

        var errorDescription: String? {
            switch self {
            case .invalidImage: return "Изображение слишком большое или повреждено."
            case .quotaExceeded: return "Лимит сохранённых изображений — 250 МБ."
            }
        }
    }
}

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var entries: [ClipboardEntry] = []
    @Published private(set) var isMonitoring = false
    @Published var lastError: String?

    var capturesImages = false
    var onImageSaved: ((URL) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        isMonitoring = true
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        timer.tolerance = 0.15
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stopAndClear() {
        timer?.invalidate()
        timer = nil
        isMonitoring = false
        entries.removeAll()
    }

    func clear() { entries.removeAll() }

    /// Системный буфер при этом не трогаем: текст там остаётся, и вставить его
    /// в другое место по-прежнему можно. Убираем только строку из истории.
    func forgetText(_ text: String) {
        let remaining = ClipboardPolicy.removingText(text, from: entries)
        guard remaining.count != entries.count else { return }
        entries = remaining
    }

    func remove(_ entry: ClipboardEntry) { entries.removeAll { $0.id == entry.id } }

    func copy(_ entry: ClipboardEntry) {
        InternalPasteboard.write(to: pasteboard) { board in
            switch entry.payload {
            case .text(let text): board.setString(text, forType: .string)
            case .file(let url): board.writeObjects([url as NSURL])
            case .image(let data): board.setData(data, forType: .png)
            }
        }
        lastChangeCount = pasteboard.changeCount

    }

    func saveImage(_ entry: ClipboardEntry) {
        guard case .image(let data) = entry.payload else { return }
        do {
            let url = try ClipboardVault.save(data)
            onImageSaved?(url)
            lastError = nil
        } catch {
            lastError = error.localizedDescription
        }
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Копию, сделанную внутри самой Curty — ⌘C в заметке, в переводе, в
        // поле поиска, — в историю класть незачем: текст и так лежит в
        // приложении, а в списке появлялся бы дубль. Признак простой: ключевое
        // окно принадлежит нам, значит копировали у нас. Наши собственные
        // команды копирования помечены отдельно, но системное ⌘C в текстовом
        // поле пометить нечем — оно проходит мимо нашего кода.
        guard NSApp.keyWindow == nil else { return }

        let typeNames = (pasteboard.types ?? []).map(\.rawValue)
        guard !ClipboardPolicy.shouldIgnore(typeNames: typeNames),
              !InternalPasteboard.containsMarker(pasteboard) else { return }

        let fileOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let url = (pasteboard.readObjects(forClasses: [NSURL.self], options: fileOptions) as? [URL])?.first {
            record(.init(payload: .file(url), capturedAt: Date()))
            return
        }

        if capturesImages, let png = normalizedPNG(), ClipboardPolicy.acceptsImage(png) {
            record(.init(payload: .image(png), capturedAt: Date()))
            return
        }

        guard let text = pasteboard.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        guard text.count <= ClipboardPolicy.maxTextCharacters else {
            lastError = "Текст длиннее \(ClipboardPolicy.maxTextCharacters) символов в историю не попадает."
            return
        }
        record(.init(payload: .text(text), capturedAt: Date()))
    }

    private func normalizedPNG() -> Data? {
        if let png = pasteboard.data(forType: .png), ClipboardPolicy.acceptsImage(png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff), ClipboardPolicy.acceptsImage(tiff),
              let bitmap = NSBitmapImageRep(data: tiff) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    /// Место в списке задаётся появлением записи и дальше не меняется:
    /// список должен оставаться там, где его оставили, а не перетасовываться
    /// от обращений к нему.
    private func record(_ entry: ClipboardEntry) {
        entries.removeAll { $0.payload == entry.payload }
        entries.insert(entry, at: 0)
        if entries.count > ClipboardPolicy.maxEntries {
            entries.removeLast(entries.count - ClipboardPolicy.maxEntries)
        }
        enforceImageBudget()
    }

    private func enforceImageBudget() {
        var total = entries.reduce(0) { $0 + $1.imageBytes }
        guard total > ClipboardPolicy.maxImageBytesTotal else { return }
        // Вытесняем самые старые картинки, текстовые записи не трогаем.
        for index in entries.indices.reversed() where entries[index].imageBytes > 0 {
            total -= entries[index].imageBytes
            entries.remove(at: index)
            if total <= ClipboardPolicy.maxImageBytesTotal { break }
        }
    }
}
